spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/restaurant
    username: postgres
    password: 4
  redis:
    url: jdbc:redis://monorail.proxy.rlwy.net:25869/0

  jpa:
    hibernate:
      ddl-auto: create

    show-sql: true

app:
  user:
    firstname: Alisher
    phone: +998900787802
    password: 123
  role:
    name: SUPER_ADMIN
  jwt:
    access:
      expiration: 3600000
      key: ae<k(eB';>~,-Q_-g:Ur!EzeO:1D@ogIKKybt#GfI~tT[KYx=k,&NJ3,C:Bc-8S
    refresh:
      expiration: 86400000
      key: dG/]A&kh/Z=4~zoijQrxzdWSnboCpqRoM!(Av^~&@ic;fN1W^T.{"wK),jG"G!>

token:
  password: 9J33guwuE0yqhwyithrr2cOAkYIsAkdJ8oiNO3Fv
  email: aliabdulloh01@mail.ru
  base-url: https://notify.eskiz.uz
  from: 4546
  urls:
    token-url: /api/auth/login
    sms-send: /api/message/sms/send